name: Run Postman Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  newman-tests:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Install Node.js
      # Node.js используется для установки Newman
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      # Step 3: Install Newman
      # Устанавливаем CLI-инструмент Newman
      - name: Install Newman
        run: |
          npm install -g newman

      # Step 4: Run Newman tests
      # Указываем путь к коллекции
      - name: Run Postman tests
        run: |
          newman run "Library Express API.postman_collection.json"
